version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    docker:
      - image: circleci/node:latest-browsers
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test

  release:
    branches:
      only: main
    docker:
      - image: circleci/node
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npx lerna version --no-private --conventional-commits --create-release github

workflows:
    build-and-test:
      jobs:
        - build-and-test
        - release:
            requires:
              - build-and-test

